// packages/solid/src/index.ts
import { createEffect, createSignal, onCleanup, onMount, type Accessor, type JSX } from 'solid-js'
import { isServer } from 'solid-js/web'
import { FilePicker as FilePickerCore } from '@anil-labs/file-picker-core'
import type { FilePickerOptions, MediaItem } from '@anil-labs/file-picker-core'

export interface UseFilePickerOptions extends FilePickerOptions {
  onSelect?: (items: MediaItem[]) => void
  onChange?: (items: MediaItem[]) => void
  onUpload?: (items: MediaItem[]) => void
  onError?: (err: unknown) => void
  onDelete?: (item: MediaItem) => void
  onOpen?: () => void
  onClose?: () => void
  onThemeChange?: (theme: 'light' | 'dark' | 'auto') => void
}

const toArray = (v: MediaItem[] | MediaItem | null | undefined): MediaItem[] =>
  v ? (Array.isArray(v) ? v : [v]) : []

const selectedKey = (v: MediaItem[] | MediaItem | null | undefined): string =>
  toArray(v)
    .map((i) => i.id)
    .join(',')

export interface FilePickerController {
  selected: Accessor<MediaItem[]>
  isOpen: Accessor<boolean>
  open: () => void
  close: () => void
  setSelected: (items: MediaItem[] | MediaItem | null) => void
  setTheme: (theme: 'light' | 'dark' | 'auto') => void
  readonly picker: FilePickerCore | null
}

/** Create and manage a FilePicker; cleans up on scope dispose. */
export function useFilePicker(options: UseFilePickerOptions): FilePickerController {
  const [selected, setSelectedSig] = createSignal<MediaItem[]>(toArray(options.selected))
  const [isOpen, setIsOpen] = createSignal(false)
  let picker: FilePickerCore | null = null

  onMount(() => {
    const p = new FilePickerCore(options)
    p.on('change', (i) => {
      setSelectedSig(i)
      options.onChange?.(i)
    })
    p.on('select', (i) => {
      setSelectedSig(i)
      options.onSelect?.(i)
    })
    p.on('upload', (i) => options.onUpload?.(i))
    p.on('delete', (i) => options.onDelete?.(i))
    p.on('error', (e) => options.onError?.(e))
    p.on('theme', (t) => options.onThemeChange?.(t))
    p.on('open', () => {
      setIsOpen(true)
      options.onOpen?.()
    })
    p.on('close', () => {
      setIsOpen(false)
      options.onClose?.()
    })
    picker = p
    onCleanup(() => p.destroy())
  })

  // Controlled selection: only push into the engine when the id set changes.
  let prevKey = selectedKey(options.selected)
  createEffect(() => {
    const key = selectedKey(options.selected)
    if (key === prevKey) return
    prevKey = key
    picker?.setSelected(options.selected ?? null)
  })

  return {
    selected,
    isOpen,
    open: () => picker?.open(),
    close: () => picker?.close(),
    setSelected: (i) => picker?.setSelected(i),
    setTheme: (t: 'light' | 'dark' | 'auto') => picker?.setTheme(t),
    get picker() {
      return picker
    },
  }
}

export interface FilePickerProps extends UseFilePickerOptions {
  label?: string
  showSelected?: boolean
}

/** A ready-made trigger + selected-thumbnails component. */
export function FilePicker(props: FilePickerProps): JSX.Element {
  // SSR-safe: never touch `document` on the server; the real wrapper (and the
  // imperative mounts below) are created only on the client.
  if (isServer || typeof document === 'undefined') return null
  const wrap = document.createElement('div')
  let core: FilePickerCore | undefined
  onMount(() => {
    core = new FilePickerCore(props)
    core.on('select', (i) => props.onSelect?.(i))
    core.on('change', (i) => props.onChange?.(i))
    core.on('upload', (i) => props.onUpload?.(i))
    const disposeTrigger = core.mountTrigger(wrap, { label: props.label })
    const disposeSelected = props.showSelected !== false ? core.mountSelected(wrap) : undefined
    onCleanup(() => {
      disposeTrigger()
      disposeSelected?.()
      core?.destroy()
      core = undefined
    })
  })
  createEffect(() => {
    if (props.theme && core) core.setTheme(props.theme)
  })
  return wrap
}

export type {
  FilePickerOptions,
  MediaItem,
  MediaFolder,
  FilePickerAdapter,
} from '@anil-labs/file-picker-core'

// packages/react/src/index.ts
'use client'
import { createElement as h, useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import { FilePicker as FilePickerCore } from '@anil-labs/file-picker-core'
import type { FilePickerOptions, MediaItem } from '@anil-labs/file-picker-core'

export interface UseFilePickerOptions extends FilePickerOptions {
  onSelect?: (items: MediaItem[]) => void
  onChange?: (items: MediaItem[]) => void
  onUpload?: (items: MediaItem[]) => void
  onError?: (err: unknown) => void
  onDelete?: (item: MediaItem) => void
  onOpen?: () => void
  onClose?: () => void
  onThemeChange?: (theme: 'light' | 'dark' | 'auto') => void
}

export interface FilePickerController {
  /** The underlying engine (null until mounted on the client). */
  picker: FilePickerCore | null
  /** Currently-selected items (reactive). */
  selected: MediaItem[]
  isOpen: boolean
  open: () => void
  close: () => void
  setSelected: (items: MediaItem[] | MediaItem | null) => void
  setTheme: (theme: 'light' | 'dark' | 'auto') => void
}

const toArray = (v: MediaItem[] | MediaItem | null | undefined): MediaItem[] =>
  v ? (Array.isArray(v) ? v : [v]) : []

/**
 * Create and manage a FilePicker instance. The picker is created on mount
 * (client-only) and destroyed on unmount; selection is mirrored into state.
 */
export function useFilePicker(options: UseFilePickerOptions): FilePickerController {
  const optionsRef = useRef(options)
  optionsRef.current = options
  const [picker, setPicker] = useState<FilePickerCore | null>(null)
  const [selected, setSelectedState] = useState<MediaItem[]>(() => toArray(options.selected))
  const [isOpen, setIsOpen] = useState(false)

  useEffect(() => {
    const p = new FilePickerCore(optionsRef.current)
    const offs = [
      p.on('change', (items) => {
        setSelectedState(items)
        optionsRef.current.onChange?.(items)
      }),
      p.on('select', (items) => {
        setSelectedState(items)
        optionsRef.current.onSelect?.(items)
      }),
      p.on('upload', (items) => optionsRef.current.onUpload?.(items)),
      p.on('delete', (item) => optionsRef.current.onDelete?.(item)),
      p.on('error', (err) => optionsRef.current.onError?.(err)),
      p.on('theme', (theme) => optionsRef.current.onThemeChange?.(theme)),
      p.on('open', () => {
        setIsOpen(true)
        optionsRef.current.onOpen?.()
      }),
      p.on('close', () => {
        setIsOpen(false)
        optionsRef.current.onClose?.()
      }),
    ]
    setPicker(p)
    return () => {
      for (const off of offs) off()
      p.destroy()
    }
    // Created once  the adapter is read at construction and callbacks use a ref.
  }, [])

  const theme = options.theme
  useEffect(() => {
    if (picker && theme) picker.setTheme(theme)
  }, [picker, theme])

  // Controlled selection: only push into the engine when the id set changes.
  const selectedKey = toArray(options.selected)
    .map((i) => i.id)
    .join(',')
  useEffect(() => {
    if (picker) picker.setSelected(options.selected ?? null)
    // Keyed on selectedKey so reference-only changes don't loop.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [picker, selectedKey])

  const open = useCallback(() => picker?.open(), [picker])
  const close = useCallback(() => picker?.close(), [picker])
  const setSelected = useCallback(
    (items: MediaItem[] | MediaItem | null) => picker?.setSelected(items),
    [picker],
  )
  const setTheme = useCallback((t: 'light' | 'dark' | 'auto') => picker?.setTheme(t), [picker])

  return { picker, selected, isOpen, open, close, setSelected, setTheme }
}

export interface FilePickerProps extends UseFilePickerOptions {
  /** Trigger label (ignored when `children` is provided). */
  label?: string
  /** Custom trigger content  clicking it opens the picker. */
  children?: ReactNode
  /** Render the selected-thumbnails strip below the trigger. @default true */
  showSelected?: boolean
  /** Class name for the wrapper element. */
  wrapperClass?: string
}

/**
 * A ready-made trigger + selected-thumbnails wrapper. For full control, use
 * {@link useFilePicker} and render your own trigger.
 */
export function FilePicker(props: FilePickerProps): ReactNode {
  const { label, children, showSelected = true, wrapperClass, ...options } = props
  const { picker, open } = useFilePicker(options)
  const selectedRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!picker || !showSelected || !selectedRef.current) return
    return picker.mountSelected(selectedRef.current)
  }, [picker, showSelected])

  const trigger = children
    ? h('span', { onClick: open, style: { display: 'inline-flex', cursor: 'pointer' } }, children)
    : h(
        'button',
        { type: 'button', className: 'fp fp-trigger', onClick: open },
        label ?? 'Select File',
      )

  return h(
    'div',
    { className: wrapperClass },
    trigger,
    showSelected ? h('div', { ref: selectedRef }) : null,
  )
}

export type {
  FilePickerOptions,
  MediaItem,
  MediaFolder,
  FilePickerAdapter,
} from '@anil-labs/file-picker-core'
